const ASSOCIATIONS = [
  {
    id: 1,
    nom_ar: "دار الحياة للبالغين — الدار البيضاء",
    nom_fr: "Maison de Vie Casablanca Adultes",
    ville_ar: "الدار البيضاء",
    ville_fr: "Casablanca",
    aide_ar: "إيواء، تغذية، نقل، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, transport, soutien psychologique et social",
    adresse_ar: "59 شارع الناظور، الدار البيضاء",
    adresse_fr: "59 Avenue de Nador, Casablanca",
    tel: "05 22 83 83 23",
    fiabilite: "verif"
  },
  {
    id: 2,
    nom_ar: "دار الحياة للأطفال — الدار البيضاء",
    nom_fr: "Maison de Vie Enfants Casablanca",
    ville_ar: "الدار البيضاء",
    ville_fr: "Casablanca",
    aide_ar: "إيواء للأطفال والمرافقين، تغذية، نقل، مرافقة الأسر",
    aide_fr: "Hébergement enfants et accompagnants, restauration, transport, accompagnement familles",
    adresse_ar: "شارع القدس، حي مولاي عبد الله، عين الشق، الدار البيضاء",
    adresse_fr: "Bd Al Qods, Hay My Abdellah, Aïn Chok, Casablanca",
    tel: "05 22 52 22 52",
    fiabilite: "verif"
  },
  {
    id: 3,
    nom_ar: "دار الحياة — مكناس",
    nom_fr: "Maison de Vie Meknès",
    ville_ar: "مكناس",
    ville_fr: "Meknès",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "مستشفى مولاي إسماعيل، مكناس",
    adresse_fr: "Hôpital My Ismail, Rue Kifa, Ville nouvelle, Meknès",
    tel: null,
    fiabilite: "verif"
  },
  {
    id: 4,
    nom_ar: "دار الحياة — فاس",
    nom_fr: "Maison de Vie Fès",
    ville_ar: "فاس",
    ville_fr: "Fès",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "المستشفى الجامعي الحسن الثاني، طريق سيدي حرازم، فاس",
    adresse_fr: "CHU Hassan II, Route de Sidi Harazem, Fès",
    tel: "05 35 61 84 22",
    fiabilite: "verif"
  },
  {
    id: 5,
    nom_ar: "دار الحياة — بني ملال",
    nom_fr: "Maison de Vie Béni Mellal",
    ville_ar: "بني ملال",
    ville_fr: "Béni Mellal",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "بني ملال",
    adresse_fr: "Béni Mellal",
    tel: null,
    fiabilite: "encours"
  },
  {
    id: 6,
    nom_ar: "دار الحياة — مراكش",
    nom_fr: "Maison de Vie Marrakech",
    ville_ar: "مراكش",
    ville_fr: "Marrakech",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "شارع الكليات أمرشيش، قرب المستشفى الجامعي محمد السادس، مراكش",
    adresse_fr: "Av. des Facultés Amerchich, proche CHU Mohammed VI",
    tel: "05 24 30 88 88",
    fiabilite: "verif"
  },
  {
    id: 7,
    nom_ar: "دار الحياة — طنجة",
    nom_fr: "Maison de Vie Tanger",
    ville_ar: "طنجة",
    ville_fr: "Tanger",
    aide_ar: "إيواء، مرافقة اجتماعية",
    aide_fr: "Hébergement, accompagnement social",
    adresse_ar: "طنجة",
    adresse_fr: "Tanger",
    tel: null,
    fiabilite: "encours"
  },
  {
    id: 8,
    nom_ar: "دار الحياة — أكادير",
    nom_fr: "Maison de Vie Agadir",
    ville_ar: "أكادير",
    ville_fr: "Agadir",
    aide_ar: "إيواء، تغذية",
    aide_fr: "Hébergement, restauration",
    adresse_ar: "قرب مستشفى الحسن الثاني، أكادير",
    adresse_fr: "Près Hôpital Hassan II, Agadir",
    tel: "05 28 84 09 05",
    fiabilite: "verif"
  },
  {
    id: 9,
    nom_ar: "دار الحياة — العيون",
    nom_fr: "Maison de Vie Laâyoune",
    ville_ar: "العيون",
    ville_fr: "Laâyoune",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "العيون",
    adresse_fr: "Laâyoune",
    tel: null,
    fiabilite: "encours"
  },
  {
    id: 10,
    nom_ar: "دار الحياة — الرباط (جمعية أصدقاء المعهد الوطني للأنكولوجيا)",
    nom_fr: "Maison de Vie Rabat — Association AMINO",
    ville_ar: "الرباط",
    ville_fr: "Rabat",
    aide_ar: "إيواء، تغذية، دعم نفسي واجتماعي",
    aide_fr: "Hébergement, restauration, soutien psychologique et social",
    adresse_ar: "بجانب المعهد الوطني للأنكولوجيا، مولاي عبد الله، الرباط",
    adresse_fr: "À côté de l'Institut National de l'Oncologie, Moulay Abdellah, Rabat",
    tel: null,
    fiabilite: "verif"
  },
  {
    id: 11,
    nom_ar: "جمعية جنات",
    nom_fr: "Association JANNAT",
    ville_ar: "الرباط",
    ville_fr: "Rabat",
    aide_ar: "إيواء، تغذية، نقل، دعم نفسي، مرافقة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير",
    aide_fr: "Hébergement, restauration, transport, soutien psychologique, accompagnement social, aide médicaments, analyses, scanners",
    adresse_ar: "أمل 2، شارع المسيرة، يعقوب المنصور، الرباط",
    adresse_fr: "Amal 2, Avenue Almassira, Yaakoub Almansour, Rabat",
    tel: "06 33 88 97 92 / 07 10 24 93 10",
    fiabilite: "assoc"
  },
  {
    id: 12,
    nom_ar: "دار بابانا في مواجهة السرطان",
    nom_fr: "Dar Babana Face au Cancer",
    ville_ar: "مراكش",
    ville_fr: "Marrakech",
    aide_ar: "إيواء، تغذية، دعم نفسي، مرافقة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير",
    aide_fr: "Hébergement, restauration, soutien psychologique, accompagnement social, aide médicaments, analyses, scanners",
    adresse_ar: "فيلا 183، تجزئة سكار، بومسمار، مراكش",
    adresse_fr: "Villa 183, Lotissement Sakar, Boumesmar, Marrakech",
    tel: "06 24 73 03 73",
    fiabilite: "assoc"
  },
  {
    id: 13,
    nom_ar: "جمعية أصدقاء مرضى السرطان سوس ماسة",
    nom_fr: "Les Amis des Malades du Cancer Souss Massa",
    ville_ar: "أكادير",
    ville_fr: "Agadir",
    aide_ar: "دعم نفسي، حملات توعية، رعاية داعمة، مرافقة اجتماعية، اتفاقيات تخفيض تكاليف الأدوية والتحاليل والسكانير",
    aide_fr: "Soutien psychologique, sensibilisation, soins de support, accompagnement social, conventions de réduction des coûts médicaments, analyses, scanners",
    adresse_ar: "حي النجاح، زنقة رقم 448، أكادير",
    adresse_fr: "Hay Annajah, Rue n°448, Agadir",
    tel: "06 63 61 18 99",
    fiabilite: "assoc"
  },
  {
    id: 14,
    nom_ar: "جمعية المستقبل",
    nom_fr: "Association L'Avenir",
    ville_ar: "الرباط",
    ville_fr: "Rabat",
    aide_ar: "دعم الأطفال المصابين بالسرطان وأسرهم، إيواء، تغذية، نقل، دعم نفسي، مساعدة على الأدوية والتحاليل والسكانير",
    aide_fr: "Soutien enfants atteints du cancer et leurs familles, hébergement, restauration, transport, soutien psychologique, aide médicaments, analyses, scanners",
    adresse_ar: "حي النهضة 2، طريق وادي أكراش، الرباط",
    adresse_fr: "Hay Nahda Groupe II, Route Oued Akrach, Rabat",
    tel: "05 37 75 41 74",
    fiabilite: "verif"
  },
  {
    id: 16,
    nom_ar: "جمعية دار زهور",
    nom_fr: "Association Dar Zhor",
    ville_ar: "الدار البيضاء",
    ville_fr: "Casablanca",
    aide_ar: "دعم نفسي، رعاية داعمة، يوغا، ورش العافية، ورش التغذية",
    aide_fr: "Soutien psychologique, soins de support, yoga, ateliers bien-être, ateliers nutrition",
    adresse_ar: "396 شارع الزرقطوني، شقة 6، الطابق الثالث، إقامة دار السلام، الدار البيضاء",
    adresse_fr: "396 Bd Zerktouni, Apt 6, 3e étage, Résidence Dar Essalam, Casablanca",
    tel: "05 20 97 26 09",
    fiabilite: "verif"
  },
  {
    id: 17,
    nom_ar: "جمعية نبض لسرطان الثدي",
    nom_fr: "Association NABD-BC2",
    ville_ar: "القنيطرة",
    ville_fr: "Kénitra",
    aide_ar: "دعم النساء المصابات بسرطان الثدي، مرافقة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير، ورش تثقيفية، دعم نفسي، مجموعات نقاش، فن العلاج، نقل (القنيطرة-الرباط)",
    aide_fr: "Soutien femmes cancer du sein, accompagnement social, aide médicaments, analyses, scanners, ateliers éducatifs, soutien psychologique, groupes de parole, art-thérapie, transport Kénitra-Rabat",
    adresse_ar: "رقم 18 زنقة عمرو بن العاص، عمارة B، القنيطرة",
    adresse_fr: "N°18 Rue Amr Ibn Ass, Imm B, Kénitra",
    tel: "07 15 30 88 27",
    fiabilite: "verif"
  },
  {
    id: 18,
    nom_ar: "جمعية أصدقاء الشريط الوردي",
    nom_fr: "Les Amis du Ruban Rose",
    ville_ar: "الدار البيضاء",
    ville_fr: "Casablanca",
    aide_ar: "الدعم النفسي للنساء المصابات بالسرطان، ورش وأنشطة اجتماعية ورياضية",
    aide_fr: "Soutien psychologique des femmes atteintes du cancer, ateliers et activités sociales et sportives",
    adresse_ar: "الدار البيضاء",
    adresse_fr: "Casablanca",
    tel: "06 45 36 03 60",
    fiabilite: "assoc"
  },
  {
    id: 19,
    nom_ar: "جمعية نسيبة",
    nom_fr: "Association Noussayba",
    ville_ar: "الرباط",
    ville_fr: "Rabat",
    aide_ar: "إيواء، تغذية، نقل للنساء المصابات بالسرطان، متابعة نفسية، مرافقة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير والكيماوي",
    aide_fr: "Hébergement, restauration, transport pour femmes atteintes du cancer, suivi psychologique, accompagnement social, aide médicaments, analyses, scanners, chimiothérapie",
    adresse_ar: "رقم 186 أمل 4، يعقوب المنصور، الرباط",
    adresse_fr: "N°186 Amal 4, Yaakoub Al Mansour, Rabat",
    tel: "05 37 79 73 87 / 06 48 96 82 98",
    fiabilite: "assoc"
  },
  {
    id: 21,
    nom_ar: "جمعية أحلام العصافير",
    nom_fr: "Association Ahlam Elaasafir",
    ville_ar: "الرباط",
    ville_fr: "Rabat",
    aide_ar: "مساعدة نفسية للأطفال المصابين بالسرطان بمساعدتهم على تحقيق أحلامهم (لقاء مشاهير، قيادة طائرة، قيادة قطار...)، أنشطة اجتماعية",
    aide_fr: "Aide psychologique aux enfants malades en réalisant leurs rêves (rencontres célébrités, piloter un avion, conduire un train...), activités sociales",
    adresse_ar: "حي يعقوب المنصور، الرباط",
    adresse_fr: "Hay Yaakoub AlMansour, Rabat",
    tel: "06 98 05 16 73",
    fiabilite: "assoc"
  },
  {
    id: 22,
    nom_ar: "جمعية الطموح لمساندة مرضى السرطان",
    nom_fr: "Association Tomouh",
    ville_ar: "الدار البيضاء",
    ville_fr: "Casablanca",
    aide_ar: "دعم نفسي، مساعدة على الأدوية والتحاليل والسكانير والكيماوي",
    aide_fr: "Soutien psychologique, aide financière médicaments, analyses, scanners, chimiothérapie",
    adresse_ar: "ديار السلام، حي الولفة، الدار البيضاء",
    adresse_fr: "Diar Assalam, Hay Aloualfa, Casablanca",
    tel: "06 79 76 22 09",
    fiabilite: "assoc"
  },
  {
    id: 23,
    nom_ar: "جمعية حليمة لمرضى السرطان",
    nom_fr: "Association Halima",
    ville_ar: "القنيطرة",
    ville_fr: "Kénitra",
    aide_ar: "دعم نفسي، مساعدة على الأدوية والتحاليل والسكانير والرنين المغناطيسي والكيماوي والإشعاعي، أنشطة اجتماعية وورش",
    aide_fr: "Soutien psychologique, aide médicaments, analyses, scanners, IRM, chimiothérapie, radiothérapie, activités sociales et ateliers",
    adresse_ar: "القنيطرة",
    adresse_fr: "Kénitra",
    tel: "06 41 48 89 91 / 06 54 67 21 80 / 07 71 66 37 77",
    fiabilite: "encours"
  },
  {
    id: 24,
    nom_ar: "جمعية السرطان... كلنا معنيون",
    nom_fr: "Association Le Cancer... Nous sommes tous concernés",
    ville_ar: "تطوان",
    ville_fr: "Tétouan",
    aide_ar: "دعم نفسي، توعية، مساعدة على الأدوية والتحاليل والسكانير والكيماوي والإشعاعي",
    aide_fr: "Soutien psychologique, sensibilisation, aide médicaments, analyses, scanners, chimiothérapie, radiothérapie",
    adresse_ar: "شارع أبو العلاء المعري، قبالة الحرس الملكي، تطوان",
    adresse_fr: "Avenue Abou Alae AL Maarri, à côté de la Garde royale, Tétouan",
    tel: "05 39 99 09 86 / 06 62 16 23 88",
    fiabilite: "verif"
  },
  {
    id: 25,
    nom_ar: "جمعية بسمة",
    nom_fr: "Association Basma",
    ville_ar: "صفرو",
    ville_fr: "Sefrou",
    aide_ar: "دعم نفسي، مرافقة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير والكيماوي والإشعاعي",
    aide_fr: "Soutien psychologique, accompagnement social, aide médicaments, analyses, scanners, chimiothérapie, radiothérapie",
    adresse_ar: "دار الشباب، طريق بولمان، صفرو",
    adresse_fr: "Maison des Jeunes, Route Boulmane, Sefrou",
    tel: "06 68 08 01 15",
    fiabilite: "assoc"
  },
  {
    id: 26,
    nom_ar: "جمعية بلسم لدعم مرضى السرطان بجهة الشرق",
    nom_fr: "Association Balsam — Région de l'Oriental",
    ville_ar: "وجدة",
    ville_fr: "Oujda",
    aide_ar: "متابعة نفسية، مساعدة على الأدوية والسكانير والتحاليل والرنين المغناطيسي وسيارة الإسعاف، نقل المرضى، أنشطة اجتماعية",
    aide_fr: "Accompagnement psychologique, aide médicaments, scanners, analyses, IRM, ambulance, transport des patients, activités sociales",
    adresse_ar: "شارع الشهداء، تجزئة بن قاشور رقم 39 (أمام حمام بن قاشور)، وجدة",
    adresse_fr: "Boulevard Achouhada, Lotissement Ben Kachour n°39, Oujda (en face Hammam Ben Kachour)",
    tel: "05 36 70 67 85 / 07 00 22 50 00",
    fiabilite: "verif"
  },
  {
    id: 27,
    nom_ar: "الجمعية المغربية لمرضى السرطان",
    nom_fr: "Association Marocaine des Patients de Cancer",
    ville_ar: "آسفي",
    ville_fr: "Safi",
    aide_ar: "دعم النساء المصابات بالسرطان، إيواء، تغذية، نقل إلى مراكز الأنكولوجيا، أنشطة اجتماعية وورش عافية",
    aide_fr: "Soutien femmes atteintes du cancer, hébergement, restauration, transport vers centres d'oncologie, activités sociales et ateliers bien-être",
    adresse_ar: "9 زنقة أزنبق، تجزئة الفردوس لوريني 2، آسفي",
    adresse_fr: "9 Rue Azinbaq, Lotissement Alfirdous Lourini 2, Safi",
    tel: "06 43 92 10 56",
    fiabilite: "assoc"
  },
  {
    id: 28,
    nom_ar: "جمعية بدر",
    nom_fr: "Association Badr",
    ville_ar: "سيدي قاسم",
    ville_fr: "Sidi Kassem",
    aide_ar: "دعم نفسي، نقل إلى مراكز الأنكولوجيا، مساعدة على الأدوية والتحاليل والسكانير، حملات توعية، ورش وأنشطة اجتماعية",
    aide_fr: "Soutien psychologique, transport vers centres d'oncologie, aide médicaments, analyses, scanners, sensibilisation, ateliers et activités sociales",
    adresse_ar: "دار الشباب المدينة، سيدي قاسم",
    adresse_fr: "Maison des Jeunes Almadina, Sidi Kassem",
    tel: "06 21 80 14 44 / 06 66 75 74 40",
    fiabilite: "assoc"
  },
  {
    id: 29,
    nom_ar: "جمعية محاربات ومحاربو السرطان",
    nom_fr: "Association Cancer Warriors",
    ville_ar: "ورزازات",
    ville_fr: "Ouarzazate",
    aide_ar: "نقل المرضى من ورزازات إلى مراكز الأنكولوجيا، مساعدات لتخفيض تكاليف التحاليل والسكانير، دعم نفسي، حملات توعية وقوافل طبية، أنشطة اجتماعية",
    aide_fr: "Transport patients de Ouarzazate vers centres d'oncologie, réduction coûts analyses, scanners, soutien psychologique, sensibilisation, caravanes médicales, activités sociales",
    adresse_ar: "تجزئة الحسنية، ورزازات",
    adresse_fr: "Lotissement Alhassania, Ouarzazate",
    tel: "06 05 22 87 31",
    fiabilite: "assoc"
  },
  {
    id: 30,
    nom_ar: "جمعية الأزهار لإيواء مرضى السرطان",
    nom_fr: "Association Alazhar pour l'hébergement des malades du cancer",
    ville_ar: "آيت أورير",
    ville_fr: "Ait Ourir",
    aide_ar: "إيواء، تغذية، نقل، مساعدة على الأدوية والسكانير والكيماوي والإشعاعي والتحاليل، ملابس العيد، مستلزمات الدخول المدرسي، دعم نفسي، أنشطة اجتماعية",
    aide_fr: "Hébergement, restauration, transport, aide médicaments, scanners, chimiothérapie, radiothérapie, analyses, habits Aid, fournitures scolaires, soutien psychologique, activités sociales",
    adresse_ar: "حي آيت منصور، آيت أورير",
    adresse_fr: "Hay Ait Mansour, Ait Ourir",
    tel: "06 51 12 97 83",
    fiabilite: "assoc"
  },
  {
    id: 31,
    nom_ar: "جمعية أمل لمرضى اللوكيميا",
    nom_fr: "Association des Malades atteints de Leucémie",
    ville_ar: "مراكش",
    ville_fr: "Marrakech",
    aide_ar: "متابعة نفسية لجميع مرضى السرطان، إيواء، تغذية، نقل إلى مراكز الأنكولوجيا، مساعدات اجتماعية (ملابس العيد، مستلزمات الدخول المدرسي، دعم الأطفال)، مساعدة على الأدوية والتحاليل، تكوين الأطباء وحملات توعية",
    aide_fr: "Suivi psychologique tous types de cancer, hébergement, restauration, transport, aides sociales (habits Aid, fournitures scolaires), aide médicaments, analyses, formation médecins, sensibilisation",
    adresse_ar: "1024 تجزئة رياض أوريكا، تاسلطانت، مراكش",
    adresse_fr: "1024 Lotissement Riad Ourika, Tasseltante, Marrakech",
    tel: "06 11 53 57 29",
    fiabilite: "assoc"
  },
  {
    id: 32,
    nom_ar: "جمعية عطاء لمرضى السرطان",
    nom_fr: "Association Ataa des patients de cancer",
    ville_ar: "المحمدية",
    ville_fr: "Mohammedia",
    aide_ar: "متابعة نفسية، أنشطة اجتماعية للمرضى، حملات توعية",
    aide_fr: "Suivi psychologique, activités sociales pour les patients, sensibilisation",
    adresse_ar: "دار الشباب، عين الحرودة، المحمدية",
    adresse_fr: "Dar Chabab, Ain Harrouda, Mohammedia",
    tel: "06 97 22 21 68",
    fiabilite: "encours"
  },
  {
    id: 33,
    nom_ar: "جمعية نحن والسرطان",
    nom_fr: "Association Le Cancer et Nous",
    ville_ar: "المحمدية",
    ville_fr: "Mohammedia",
    aide_ar: "مرافقة نفسية لمرضى السرطان وأسرهم، مرافقة في مراكز الأنكولوجيا، زيارات للمرضى",
    aide_fr: "Accompagnement psychologique des malades et familles, accompagnement dans les centres d'oncologie, visites aux malades",
    adresse_ar: "دار الشباب العربي، المحمدية",
    adresse_fr: "Dar Achabab AlArabi, Mohammedia",
    tel: "06 03 60 65 21",
    fiabilite: "encours"
  },
  {
    id: 34,
    nom_ar: "جمعية الباب الكبير لمرضى السرطان",
    nom_fr: "Association Albab Lkbir des patients de cancer",
    ville_ar: "خريبكة",
    ville_fr: "Khouribga",
    aide_ar: "مرافقة نفسية، نقل إلى مراكز الأنكولوجيا، قوافل الكشف المبكر، حملات توعية، أنشطة اجتماعية، مساعدة على الأدوية والتحاليل والسكانير والكيماوي والإشعاعي",
    aide_fr: "Accompagnement psychologique, transport vers centres d'oncologie, caravanes dépistage, sensibilisation, activités sociales, aide médicaments, analyses, scanners, chimiothérapie, radiothérapie",
    adresse_ar: "شارع مولاي يوسف، عمارة سمار، بجانب الصندوق الوطني للضمان الاجتماعي، خريبكة",
    adresse_fr: "Avenue Moulay Youssef, Imm Smar, à côté de CNSS, Khouribga",
    tel: "06 29 74 02 04",
    fiabilite: "assoc"
  },
  {
    id: 35,
    nom_ar: "جمعية البلسم لتعزيز الصحة والعمل الاجتماعي",
    nom_fr: "Association Albalsam pour la promotion de la santé et de l'action sociale",
    ville_ar: "القنيطرة",
    ville_fr: "Kénitra",
    aide_ar: "حملات الكشف المبكر عن سرطان الثدي والرحم وقوافل طبية، دعم المرضى في الوصول إلى مراكز العلاج العمومية والخاصة والفحوصات والعلاجات",
    aide_fr: "Campagnes dépistage cancer du sein et de l'utérus, caravanes médicales, appui accès aux structures de traitement publiques et privées",
    adresse_ar: "مسجد الريان، أولاد أوجيه هدادة، القنيطرة",
    adresse_fr: "Mosquée Ar-Rayan, Ouled Oujih Hadada, Kénitra",
    tel: "07 67 18 48 46",
    fiabilite: "assoc"
  },
  {
    id: 37,
    nom_ar: "جمعية ابتسامة لدعم مرضى السرطان — كلميم",
    nom_fr: "Association Ibtissama pour le travail social et la lutte contre le cancer",
    ville_ar: "كلميم",
    ville_fr: "Guelmim",
    aide_ar: "حملات الكشف المبكر عن السرطان وقوافل طبية، مرافقة المرضى في مراكز العلاج، نقل، مساعدة على الأدوية والتحاليل والسكانير، دعم نفسي، أنشطة اجتماعية",
    aide_fr: "Campagnes dépistage et caravanes médicales, accompagnement patients dans les centres, transport, aide médicaments, analyses, scanners, soutien psychologique, activités sociales",
    adresse_ar: "الطابق الثاني، عمارة الشيكر، شارع محمد السادس، كلميم",
    adresse_fr: "Immeuble Chiguer, Avenue Mohamed VI, Guelmim (2e étage)",
    tel: "06 61 20 39 83",
    fiabilite: "assoc"
  }
];
